<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container4ZffLGa\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container4ZffLGa/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container4ZffLGa.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container4ZffLGa\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container4ZffLGa\App_KernelDevDebugContainer([
    'container.build_hash' => '4ZffLGa',
    'container.build_id' => '2341e982',
    'container.build_time' => 1622539199,
], __DIR__.\DIRECTORY_SEPARATOR.'Container4ZffLGa');
